// config.js — all tunable constants for "Invasion of the Vatican".
// Single source of truth for balancing (spec §10). Phase 1 only consumes the
// board/render constants; the rest are defined now so later phases can use them.

// --- Board dimensions (spec §3, §10) ---
// The logic grid is now derived from the real Vatican map in data/map-data.js
// (generated by tools/build-map.mjs from OpenStreetMap). board.js re-exports the
// authoritative cols/rows from that data; these values are kept in sync for any
// other consumer and as documentation. A finer grid than the original 100×50 is
// used so real streets/buildings resolve cleanly — movement/range (below) can be
// retuned to taste; they are intentionally independent of grid resolution.
export const GRID_COLS = 200; // board width in tiles  (≈ 8 m per tile)
export const GRID_ROWS = 146; // board height in tiles
export const TILE_SIZE = 10;  // pixel size of one tile in world space

// --- Unit stats (spec §4, §10) ---
export const SOLDIER_HP = 10;
export const TANK_HP = 30;

// Phase 8 Part D — SPEC CHANGE (overrides §4/§10): soldier move ×1.3, rounded to
// the nearest whole tile (6→8 via 7.8; 10→13). Targeting radius is unchanged.
export const SOLDIER_MOVE_ACT = 8;   // soldier move when it will also act (was 6)
export const SOLDIER_MOVE_ONLY = 13; // soldier move when forgoing its action (was 10)
export const TANK_MOVE = 15;         // tank move (then act)

export const SOLDIER_RADIUS = 4;  // soldier targeting radius (Chebyshev)
export const TANK_RADIUS = 10;    // tank targeting radius (Chebyshev)

// --- Action effects (spec §6, §10) ---
export const RIFLEMAN_DMG = 5;  // rifleman damage
export const TANK_DMG = 10;     // tank-result damage
export const STAR_HEAL = 10;    // green-star heal amount (capped at max HP)

// --- Army composition (spec §4, §10) ---
// Phase 8 Part C — SPEC CHANGE: placement is now UNCAPPED (both sides place any
// number of soldiers + tanks). These counts are kept only as a default/suggested
// composition (and for the Node probes); the live game ignores them as caps.
export const ITALY_SOLDIERS = 15;
export const ITALY_TANKS = 4;
export const VATICAN_SOLDIERS = 10;

// Phase 8 Part C: Start is enabled once each side has at least this many units.
export const MIN_UNITS_TO_START = 1;

// --- Wheel of fortune (spec §5, §10) ---
// Phase 8 Part E — SPEC CHANGE (overrides §5): 8 equal 45° wedges, surrender flag
// REMOVED, plus the two double-attacks (rifle2/tank2) and capture. Composition:
// 2× rifleman, 1× rifle2, 1× tank, 1× tank2, 1× grenade, 1× star, 1× capture.
// The two plain riflemen sit OPPOSITE each other (indices 0 & 4 on the 8-wheel),
// keeping rifleman the most likely single result (2/8); every other is 1/8.
export const WHEEL_WEDGES = [
  'rifleman', // 0
  'rifle2',   // 1
  'tank',     // 2
  'tank2',    // 3
  'rifleman', // 4  (opposite index 0)
  'grenade',  // 5
  'star',     // 6
  'capture',  // 7
];
export const SPIN_DURATION_MS = 4000; // spin/deceleration time (~4s, ease-out)

// Per-wedge wheel colors (spec §5): rifleman blue, tank olive, grenade gunmetal,
// green star green; the ×2 variants are brighter siblings, capture a distinct
// purple. Tunable like everything else here.
export const WHEEL_COLORS = {
  rifleman: '#3b6fd0', // blue
  rifle2: '#5b97f0',   // brighter blue (rifle ×2)
  tank: '#6f7a2e',     // olive green
  tank2: '#9aa83e',    // brighter olive (tank ×2)
  grenade: '#3c4348',  // dark gunmetal
  star: '#3fae54',     // green
  capture: '#8e44ad',  // purple
};
// How many whole turns the wheel spins (random within this range → random
// initial speed for the fixed ~SPIN_DURATION_MS ease-out). Landing is a separate
// uniform offset, so the result distribution stays uniform (rifleman 2/6).
export const WHEEL_MIN_TURNS = 4;
export const WHEEL_MAX_TURNS = 7;

// --- Sides ---
export const SIDE = {
  ITALY: 'italy',     // attackers, blue
  VATICAN: 'vatican', // defenders, yellow
};

// --- Terrain types (each map tile carries one) ---
export const TERRAIN = {
  STREET: 'street',     // street / plaza — walkable
  GARDEN: 'garden',     // park / garden / green — walkable
  BASILICA: 'basilica', // basilica interior — walkable (enter via gate)
  BUNKER: 'bunker',     // religious/symbolic building interior — walkable (enter via gate)
  BUILDING: 'building', // building footprint — blocked
  WALL: 'wall',         // perimeter wall — blocked
  GATE: 'gate',         // gate in a wall — walkable
  WATER: 'water',       // water / fountain — blocked
};

// --- Palette (spec §3, §8): light, vivid, map-like ---
// The board is now drawn from real OSM vector geometry (areas + street lines),
// so colors are organized as a small map style. Bright but legible.
export const COLORS = {
  bg: '#e9e2d0',          // open ground / outside features
  gridLine: 'rgba(40, 40, 40, 0.10)',

  // sides (unit tints, used from Phase 2 on)
  italy: '#2563b0',       // blue — Italian attackers
  vatican: '#e8c61e',     // yellow — Vatican defenders

  // Phase 3 move preview (spec §8.1): muted, semi-transparent green reachable set.
  moveOverlay: 'rgba(74, 175, 80, 0.30)',     // reachable-tile fill
  moveOverlayEdge: 'rgba(46, 125, 50, 0.45)', // reachable-tile outline

  // Phase 5 attack preview (spec §8.1): muted semi-transparent red attack radius
  // (the Chebyshev square minus blocked tiles), with valid targets emphasized.
  attackOverlay: 'rgba(198, 57, 43, 0.16)',     // attack-radius fill (muted)
  attackOverlayEdge: 'rgba(150, 30, 20, 0.28)', // attack-radius outline
  targetOverlay: 'rgba(214, 48, 36, 0.42)',     // valid-target fill (emphasized)
  targetOverlayEdge: 'rgba(140, 12, 4, 0.95)',  // valid-target outline
};

// --- Phase 7: per-unit HP bar (spec §8) ---
// Sizes are in WORLD px (TILE_SIZE world px per tile); the bar scales with the
// icon when units are split-rendered on a shared tile, and the canvas zoom scales
// it further on screen. The fill snaps to whole HP points (effects.hpFillRatio)
// and is colored by ratio over a dark, outlined track for low-zoom legibility.
export const HPBAR = {
  widthFrac: 0.74,   // bar width as a fraction of the icon's effective size
  height: 1.8,       // bar height (world px)
  offset: 1.5,       // gap between the bar's bottom and the icon top (world px)
  radius: 0.6,       // rounded-corner radius (world px)
  track: 'rgba(26, 22, 16, 0.85)',  // dark track behind the colored fill
  outline: 'rgba(0, 0, 0, 0.72)',   // outline so the bar reads when zoomed out
  outlineW: 0.4,                    // outline width (world px)
  tick: 'rgba(0, 0, 0, 0.30)',      // per-HP-point separator ticks
  minTickPx: 0.5,                   // skip ticks finer than this (e.g. tank's 30)
  green: '#46c25a',
  amber: '#e6b23a',
  red: '#df3b2b',
  amberAt: 0.5,      // fill ratio ≤ this → amber
  redAt: 0.25,       // fill ratio ≤ this → red
};

// HP-change tween (spec §8 "animate HP changes"): the renderer keeps a displayed
// HP per unit and eases it toward the real hp over ~this long (ease-out drain on
// damage / refill on heal), synced with the flash + heal bubbles.
export const HP_TWEEN_MS = 250;

// Damaged-unit red-tint flash (spec §8): a brief red wash over the struck icon.
export const DAMAGE_FLASH_MS = 300;
export const DAMAGE_FLASH_COLOR = '220, 40, 30'; // rgb; alpha is animated

// Phase 8 Part G: capture flourish — a quick expanding ring in the captor's color
// over the captured tank's tile.
export const CAPTURE_FLASH_MS = 650;

// Movement/rotation animation (render.js visual layer). A unit slides along its
// shortest path at a constant tiles/sec, with the total A→B time clamped to a
// cinematic window so short hops aren't instant and long dashes aren't a blur.
// TURN_MS is the heading-ease time-constant — used both for cornering mid-path
// and for the "aim" turn before an attack (a quick, shortest-arc rotation).
export const MOVE_PER_TILE_MS = 280; // travel time per path step (pre-clamp)
export const MOVE_MIN_MS = 2500;     // floor: even a 1-tile move is deliberate
export const MOVE_MAX_MS = 3500;     // cap: a full-allowance dash tops out here
export const TURN_MS = 200;          // heading ease (~quick aim turn / cornering)

// Heal "+"-in-circle bubbles floating up from the unit on a green star (spec §8).
export const HEAL_BUBBLE = {
  count: 3,          // bubbles per heal
  durationMs: 950,   // lifetime of each bubble
  staggerMs: 130,    // delay between successive bubbles
  rise: 15,          // how far each floats up (world px)
  radius: 2.6,       // bubble circle radius (world px)
  spread: 3.2,       // horizontal jitter (world px)
  fill: '63, 174, 84', // rgb of the green bubble; alpha is animated
  text: '#ffffff',
};

// Tile-stacking split-render (spec §8): padding factor shrinking each split icon
// so 2+ on a tile don't touch (a lone unit still fills its tile).
export const STACK = { pad: 0.9 };

// Map style for the vector renderer: per feature class, fill / stroke / width.
export const MAP_STYLE = {
  garden: { fill: '#bfe09a', stroke: '#9cc870', strokeW: 0.6 },
  plaza: { fill: '#efe9da', stroke: '#ddd2ba', strokeW: 0.4 },
  water: { fill: '#a7d6ec', stroke: '#79b9d8', strokeW: 0.6 },
  building: { fill: '#e6dcc7', stroke: '#c7b794', strokeW: 0.5 },
  bunker: { fill: '#ecd9b0', stroke: '#c9a86a', strokeW: 0.7 }, // religious/symbolic landmarks
  basilica: { fill: '#f1d886', stroke: '#c79a37', strokeW: 1.0 },
  // streets are lines: casing drawn under a lighter fill for a real-map look
  street: { fill: '#fdfaf2', casing: '#d7cbab' },
  wall: { stroke: '#9a8a6f' },
  // gate marker: a darker "doorway" notch drawn on each gate tile so the
  // walkable openings in walls / structure perimeters stand out.
  gate: { fill: 'rgba(74, 47, 20, 0.78)', stroke: 'rgba(40, 24, 8, 0.9)' },
};

// --- Camera / viewport (Phase 1 panning) ---
export const ZOOM_MIN = 0.4;
export const ZOOM_MAX = 2.5;
export const ZOOM_STEP = 1.1; // multiplier per wheel notch
