// storage.js — Phase 8 Part A: state persistence over localStorage.
//
// A single key holds the JSON-encoded game snapshot (game logic only — never the
// OSM map, which is static and regenerated by tools/build-map.mjs). Every call is
// wrapped in try/catch so a private-mode / quota'd / unavailable localStorage
// fails silently rather than breaking the game.

const KEY = 'vatican-game:v1';

// Persist a snapshot (game.snapshot()). Silently no-ops if storage is unavailable.
export function saveState(snapshot) {
  try {
    localStorage.setItem(KEY, JSON.stringify(snapshot));
  } catch {
    /* storage unavailable / quota'd — fail silently */
  }
}

// Load the saved snapshot, or null if none / unreadable.
export function loadState() {
  try {
    const raw = localStorage.getItem(KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

// Wipe the saved game (New Game button).
export function clearState() {
  try {
    localStorage.removeItem(KEY);
  } catch {
    /* fail silently */
  }
}
